// GENERATED by scripts/photos/build-photos.mjs (npm run photos) — do not edit by hand.
import type { PhotoEntry } from './photos'

export const PHOTOS: Record<string, PhotoEntry> = {
  "hero": {
    "width": 2400,
    "height": 1300,
    "alt": "A South Indian woman in a casual linen shirt. Moving the pointer over her reveals her virtually trying on a red and gold Kanchipuram silk saree.",
    "clean": [
      {
        "src": "/images/models/hero/south-indian-fashion-clean.webp",
        "width": 2400
      },
      {
        "src": "/images/models/hero/south-indian-fashion-clean-1600.webp",
        "width": 1600
      },
      {
        "src": "/images/models/hero/south-indian-fashion-clean-800.webp",
        "width": 800
      }
    ],
    "ai": [
      {
        "src": "/images/models/hero/south-indian-fashion-ai.webp",
        "width": 2400
      },
      {
        "src": "/images/models/hero/south-indian-fashion-ai-1600.webp",
        "width": 1600
      },
      {
        "src": "/images/models/hero/south-indian-fashion-ai-800.webp",
        "width": 800
      }
    ],
    "hint": "Move across her to try on the saree",
    "touchHint": "Touch and drag to try on the saree",
    "pairLabel": "Casual ↔ Saree try-on",
    "cursorLabel": "Try on",
    "scan": [
      {
        "src": "/images/models/hero/south-indian-fashion-scan-1600.webp",
        "width": 1600
      },
      {
        "src": "/images/models/hero/south-indian-fashion-scan-800.webp",
        "width": 800
      }
    ],
    "mask": "/images/models/hero/south-indian-fashion-mask.webp"
  }
}
